### PR TITLE
consistent terminology

### PR DESCRIPTION
**Pull request by jbrannst**
containers -> application servers

### CODE REVIEW

**Comment by danieloh30** [comment]
Containers mean not only app servers but also servlet containers. See:
https://access.redhat.com/documentation/en-us/red_hat_application_migration_toolkit/4.2/html-single/web_console_guide/index#about_rhamt

**Comment by jbrannst** [comment]
It is not clear that you are referring to that context in the guide. It is not a common terminology if your are talking in a linux container context. Then you use "java container" or "Servlet container" or "EJB container" for disambiguation. Application Server is clear for everyone -- but we can of course choose ambiguity if we prefer.

**Comment by danieloh30** [comment]
RHAMT enables Java developers to migrate existing Java applications for running different runtimes and/or middlewares. I'm not saying Linux container but it's multiple runtimes/middlewares. I don't think it's only App servers. Developers can migrate the OpenJDK version too. So if you want to improve the context more clear, it would be better to runtimes/middlewares.

**Comment by jbrannst** [comment]
Yes good point

**Pull request closed without merging**
