### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by jbrannst**
spelling fix

### CODE REVIEW

**Comment by danieloh30** [comment]
There is no typo like this. Please make sure to pull the latest.

**Comment by jbrannst** [comment]
Your comment makes no sense. Look at the diff and make the fix yourself if its easier, but the grammar is just not correct and we could just fix it.

**Comment by danieloh30** [comment]
It means I can't find the wrong grammar in the instruction:
https://raw.githubusercontent.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-guides/master/migrate-to-jboss-eap.md

Are you referring to the latest repo?

**Comment by jbrannst** [comment]
It is in that file you refer to. I opened the link and it's there. It's very small though, that's how it got there, but it's there.

Try searching for the whole phrase:

> JBoss EAP provides and even more efficient and declarative way

**Comment by danieloh30** [comment]
Got it. Thanks for your contribution!

**Comment by danieloh30** [comment]
It's duplicated with https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-guides/pull/22

**Pull request merged**
